[server]
# gRPC server parameters
host = "0.0.0.0"
port = 50051
# Limitting recognition queue
queue_limit = 200

[yolo_beers]
cfg = "../data/beers.cfg"
# Path to weights file
weights = "../data/beers.weights"
# Threshold should not be < 0.0
threshold = 0.3